package com.example.muscleiq.ui.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.muscleiq.data.model.User
import com.example.muscleiq.data.repository.AuthRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

sealed class AuthState {
    object Idle : AuthState()
    object Loading : AuthState()
    object OtpSent : AuthState()
    data class Success(val user: User) : AuthState()
    data class Error(val message: String) : AuthState()
}

class AuthViewModel(
    private val authRepository: AuthRepository = AuthRepository()
) : ViewModel() {

    private val _authState = MutableStateFlow<AuthState>(AuthState.Idle)
    val authState: StateFlow<AuthState> = _authState.asStateFlow()

    fun login(email: String, pass: String) {
        if (email.isBlank() || pass.isBlank()) {
            _authState.value = AuthState.Error("Please fill in all fields")
            return
        }
        
        val emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$".toRegex()
        if (!email.matches(emailRegex)) {
            _authState.value = AuthState.Error("Please enter a valid email address")
            return
        }

        _authState.value = AuthState.Loading
        viewModelScope.launch {
            val result = authRepository.login(email, pass)
            result.onSuccess { user ->
                _authState.value = AuthState.Success(user)
            }.onFailure { error ->
                _authState.value = AuthState.Error(error.localizedMessage ?: "Login Failed")
            }
        }
    }

    fun register(name: String, email: String, pass: String) {
        if (name.isBlank() || email.isBlank() || pass.isBlank()) {
            _authState.value = AuthState.Error("Please fill in all fields")
            return
        }
        
        val emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$".toRegex()
        if (!email.matches(emailRegex)) {
            _authState.value = AuthState.Error("Please enter a valid email address")
            return
        }

        if (pass.length < 6) {
            _authState.value = AuthState.Error("Password must be at least 6 characters long")
            return
        }

        // Generate and send OTP instead of direct registration
        _authState.value = AuthState.Loading
        viewModelScope.launch {
            val result = authRepository.sendOtp(email)
            result.onSuccess {
                _authState.value = AuthState.OtpSent
            }.onFailure { error ->
                _authState.value = AuthState.Error(error.localizedMessage ?: "Failed to send OTP")
            }
        }
    }

    fun verifyOtpAndRegister(name: String, email: String, pass: String, code: String) {
        if (code.isBlank() || code.length != 6) {
            _authState.value = AuthState.Error("Please enter a valid 6-digit OTP")
            return
        }
        
        _authState.value = AuthState.Loading
        viewModelScope.launch {
            val verifyResult = authRepository.verifyOtp(email, code)
            verifyResult.onSuccess {
                // OTP verified, now create Firebase account
                val regResult = authRepository.register(name, email, pass)
                regResult.onSuccess { user ->
                    _authState.value = AuthState.Success(user)
                }.onFailure { error ->
                    _authState.value = AuthState.Error(error.localizedMessage ?: "Registration Failed after OTP")
                }
            }.onFailure { error ->
                _authState.value = AuthState.Error(error.localizedMessage ?: "Invalid or Expired OTP")
            }
        }
    }

    fun resetState() {
        _authState.value = AuthState.Idle
    }
    
    fun isUserLoggedIn(): Boolean {
        return authRepository.getCurrentUserId() != null
    }

    fun sendPasswordResetEmail(email: String) {
        if (email.isBlank()) {
            _authState.value = AuthState.Error("Please enter your email address first")
            return
        }
        _authState.value = AuthState.Loading
        viewModelScope.launch {
            val result = authRepository.sendPasswordResetEmail(email)
            result.onSuccess {
                _authState.value = AuthState.Error("Password reset link sent! Please check your email.")
            }.onFailure { error ->
                _authState.value = AuthState.Error(error.localizedMessage ?: "Failed to send reset email")
            }
        }
    }

    fun signInWithGoogle(activity: android.app.Activity) {
        _authState.value = AuthState.Loading
        viewModelScope.launch {
            try {
                val credentialManager = androidx.credentials.CredentialManager.create(activity)
                
                // Read web client ID from strings generated by google-services.json
                val resId = activity.resources.getIdentifier("default_web_client_id", "string", activity.packageName)
                if (resId == 0) {
                    _authState.value = AuthState.Error("Google Sign-In not configured in Firebase. Please enable it in Firebase Console and re-download google-services.json.")
                    return@launch
                }
                val webClientId = activity.getString(resId)
                
                val googleIdOption = com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption.Builder(webClientId)
                    .build()
                    
                val request = androidx.credentials.GetCredentialRequest.Builder()
                    .addCredentialOption(googleIdOption)
                    .build()
                    
                val result = credentialManager.getCredential(
                    request = request,
                    context = activity
                )
                
                val credential = result.credential
                if (credential is androidx.credentials.CustomCredential &&
                    credential.type == com.google.android.libraries.identity.googleid.GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                    
                    val googleIdTokenCredential = com.google.android.libraries.identity.googleid.GoogleIdTokenCredential.createFrom(credential.data)
                    val authCredential = com.google.firebase.auth.GoogleAuthProvider.getCredential(googleIdTokenCredential.idToken, null)
                    
                    val signInResult = authRepository.signInWithCredential(authCredential)
                    signInResult.onSuccess { user ->
                        _authState.value = AuthState.Success(user)
                    }.onFailure { e ->
                        _authState.value = AuthState.Error(e.localizedMessage ?: "Firebase auth failed")
                    }
                } else {
                    _authState.value = AuthState.Error("Unexpected credential type")
                }
            } catch (e: Exception) {
                _authState.value = AuthState.Error(e.localizedMessage ?: "Google Sign-In failed. Check Firebase setup.")
            }
        }
    }

    fun startPhoneNumberVerification(
        activity: android.app.Activity, 
        phoneNumber: String,
        onCodeSent: (String) -> Unit,
        onError: (String) -> Unit
    ) {
        _authState.value = AuthState.Loading
        val options = com.google.firebase.auth.PhoneAuthOptions.newBuilder(com.google.firebase.auth.FirebaseAuth.getInstance())
            .setPhoneNumber(phoneNumber)
            .setTimeout(60L, java.util.concurrent.TimeUnit.SECONDS)
            .setActivity(activity)
            .setCallbacks(object : com.google.firebase.auth.PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
                override fun onVerificationCompleted(credential: com.google.firebase.auth.PhoneAuthCredential) {
                    viewModelScope.launch {
                        val result = authRepository.signInWithCredential(credential)
                        result.onSuccess { user ->
                            _authState.value = AuthState.Success(user)
                        }.onFailure {
                            _authState.value = AuthState.Error(it.localizedMessage ?: "Auto-verification failed")
                        }
                    }
                }

                override fun onVerificationFailed(e: com.google.firebase.FirebaseException) {
                    _authState.value = AuthState.Idle
                    onError(e.localizedMessage ?: "Verification Failed")
                }

                override fun onCodeSent(
                    verificationId: String,
                    token: com.google.firebase.auth.PhoneAuthProvider.ForceResendingToken
                ) {
                    _authState.value = AuthState.Idle
                    onCodeSent(verificationId)
                }
            })
            .build()
        com.google.firebase.auth.PhoneAuthProvider.verifyPhoneNumber(options)
    }

    fun verifyOtpAndSignIn(verificationId: String, smsCode: String) {
        _authState.value = AuthState.Loading
        val credential = com.google.firebase.auth.PhoneAuthProvider.getCredential(verificationId, smsCode)
        viewModelScope.launch {
            val result = authRepository.signInWithCredential(credential)
            result.onSuccess { user ->
                _authState.value = AuthState.Success(user)
            }.onFailure {
                _authState.value = AuthState.Error(it.localizedMessage ?: "Invalid OTP")
            }
        }
    }

}
